project:
  type: website
  output-dir: docs


website:
  title: "Le muse girovaghe"
  navbar:
    right:
      - text: Monserrat Olavarria Balmaceda
        href: https://monserrat.olavarria.it
      - text: Per le scuole
        href: corsi.qmd
      - text: Spettacoli
        href: spettacoli.qmd
      - text: Contatti
        href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



